sudo: false
language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - ninja-build
    - libboost-all-dev

install: source .travis/install.sh

script:
  - BUILD_DIR="${TRAVIS_BUILD_DIR}/build_cmake"
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake -G Ninja ..
  - ninja -j4
  - ctest --verbose
