sudo: false
language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - ninja-build
    - libboost-all-dev

install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script:
  - mkdir build && cd build
  - cmake -G Ninja ..
  - ninja -j4
  - ctest --output-on-failure
